# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React App CI 

on:
  push:
    branches:
    - main
    - releases/*
  pull_request:
    branches:
    - main
    - release/*
    
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  
  upload-build:
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm install and build
      run: |
        npm install
        npm run build
    - uses: actions/upload-artifact@v2
      with: 
        name: ${{ github.workflow }}
        path: build/
